name: Publish to pub.dev

on:
  push:
    tags:
      # Must align with the tag-pattern configured on pub.dev, e.g., 'v{{version}}'
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    permissions:
      id-token: write
      contents: read
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
  # To require a GitHub Environment, configure it on pub.dev and then add:
  # with:
  #   environment: pub.dev
  #   working-directory: .
