# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release (bump and tag)

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Version bump type or explicit version (patch/minor/major or 1.2.3)"
        required: true
        default: patch

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Format check
        run: dart format --output=none --set-exit-if-changed .

      - name: Publish dry-run
        run: dart pub publish --dry-run

      - name: Bump version in pubspec.yaml
        id: bump
        run: |
          NEW_VER=$(dart run tool/bump_version.dart "${{ github.event.inputs.bump }}")
          echo "new_version=$NEW_VER" >> $GITHUB_OUTPUT

      - name: Ensure version changed
        run: |
          CURRENT=$(grep '^version:' pubspec.yaml | awk '{print $2}')
          if [ "v$CURRENT" != "v${{ steps.bump.outputs.new_version }}" ]; then
            echo "Version in pubspec.yaml is $CURRENT but bump script reported ${{ steps.bump.outputs.new_version }}"
            exit 1
          fi

      - name: Commit version bump
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add pubspec.yaml
          git commit -m "chore: bump version to ${{ steps.bump.outputs.new_version }}"

      - name: Create tag
        run: |
          git tag v${{ steps.bump.outputs.new_version }}

      - name: Push changes and tag
        run: |
          git push origin HEAD:master
          git push origin v${{ steps.bump.outputs.new_version }}
